#!/usr/bin/env python3
"""Build the dramatically expanded SSAP / ASC 944 / PCAOB catalogs.

Reads the existing detailed entries (kept verbatim, only adding
source_link), then synthesises brief-but-complete entries to cover the
full standards ranges:
  - SSAP: 1 – 122 (NAIC AP&P Manual)
  - ASC 944 sub-topics: 944-10 through 944-825
  - PCAOB AS: full insurance-relevant list

Every entry ships the four required sections + source_link.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONT = ROOT / "frontend/assets/data"
BACK = ROOT / "backend/app/data"

NAIC_BASE = "https://content.naic.org/sites/default/files/inline-files"
FASB_BASE = "https://asc.fasb.org/topic&trid=2156436"
PCAOB_BASE = "https://pcaobus.org/oversight/standards/auditing-standards"


# ---------------------------------------------------------------------------
# SSAP — full 1 to 122 range
# ---------------------------------------------------------------------------

# (number, title, fsli, summary, chapter_content, need, evolution_year_change_pairs, comparison_triples)
# comparison_triples: list of (aspect, gaap, stat, delta)
SSAP_ENTRIES = [
    ("6", "Uncollected Premium Balances, Bills Receivable for Premiums", "Receivables",
     "Premium receivables and bills receivable. Aged-receivable non-admission rule.",
     "SSAP No. 6 covers premium-receivable accounting. Premium balances over 90 days past due (or 15 days for personal lines) are non-admitted, reducing surplus. Bills receivable from agents and brokers follow similar rules.",
     "Maintains surplus integrity by removing receivables unlikely to be collected.",
     [("2001", "Original SSAP 6 issued."), ("2014", "Aging-non-admission thresholds harmonized.")],
     [("Allowance method", "ASC 326 CECL", "90-day non-admission cliff", "GAAP allowance; STAT cliff")]),
    ("9", "Subsequent Events", "Disclosure",
     "Recognition vs disclosure of events occurring between balance-sheet date and statement issuance.",
     "SSAP No. 9 distinguishes recognized subsequent events (conditions existing at balance sheet) from non-recognized (new conditions). Disclosure required for material non-recognized events.",
     "Provides users with information about post-balance-sheet developments material to interpreting the financial statements.",
     [("2001", "Original SSAP 9 issued."), ("2014", "Aligned with ASC 855.")],
     [("Recognition vs disclosure", "ASC 855 — same framework", "Same", "Aligned")]),
    ("15", "Debt and Holding Company Obligations", "Debt",
     "Long-term debt and holding-company-issued obligations. Interest accrual and disclosure.",
     "SSAP No. 15 covers traditional debt and holding-company obligations issued by insurance entities or their affiliates.",
     "Provides consistent measurement and disclosure of insurer debt.",
     [("2001", "Original SSAP 15 issued.")],
     [("Long-term debt", "Amortized cost", "Same", "Aligned")]),
    ("16R", "Electronic Data Processing Equipment and Software", "EDP/Software",
     "Capitalization and amortization of EDP equipment and software.",
     "SSAP No. 16R requires software and EDP equipment to be capitalized when meeting the recognition criteria. Operating software amortized over useful life. Non-operating (administrative) software is non-admitted.",
     "Limits surplus credit for IT investments to those directly supporting policy-administration operations.",
     [("2001", "Original SSAP 16 issued."), ("2014", "Revised (16R) for cloud-computing arrangements.")],
     [("Internal-use software", "ASC 350-40", "16R with non-admit overlay", "STAT haircuts non-operating")]),
    ("17", "Preoperating and Research and Development Costs", "R&D",
     "R&D and preoperating costs are expensed as incurred.",
     "SSAP No. 17 mandates expensing of R&D and preoperating costs — no capitalization allowed.",
     "Conservatism: R&D outcomes are uncertain; capitalization could inflate surplus.",
     [("2001", "Original SSAP 17 issued.")],
     [("R&D", "ASC 730 — expense (with limited software exceptions)", "Always expense", "STAT stricter")]),
    ("19", "Furniture, Fixtures, Equipment and Leasehold Improvements", "PP&E",
     "Furniture, fixtures, equipment, and leasehold improvements are non-admitted.",
     "SSAP No. 19 makes furniture, fixtures, equipment, and leasehold improvements non-admitted assets — they reduce surplus.",
     "Statutory accounting focuses on assets that can be liquidated to pay claims; physical office assets cannot.",
     [("2001", "Original SSAP 19 issued.")],
     [("PP&E recognition", "ASC 360 — capitalize and depreciate", "Non-admitted", "Direct surplus haircut")]),
    ("20", "Nonadmitted Assets", "Non-admitted",
     "Catalog of assets that are non-admitted under SAP regardless of other recognition rules.",
     "SSAP No. 20 enumerates non-admitted asset categories — furniture, prepaid expenses, certain receivables, restricted cash, software, and others.",
     "Provides a single reference point for non-admitted asset categorization.",
     [("2001", "Original SSAP 20 issued.")],
     [("Non-admission catalog", "Various ASC topics", "SSAP 20 + line-item SSAPs", "STAT-only construct")]),
    ("21R", "Other Admitted Assets", "Other Assets",
     "Catch-all category for admitted assets not addressed elsewhere.",
     "SSAP No. 21R provides recognition criteria for admitted assets that don't fall under other SSAPs — including surplus debentures and certain receivables.",
     "Closes gaps in the admitted-asset framework.",
     [("2001", "Original SSAP 21 issued."), ("2018", "Revised (21R).")],
     [("Other assets", "ASC 350 / various", "SSAP 21R", "Generally aligned")]),
    ("23", "Foreign Currency Transactions and Translations", "FX",
     "Foreign-currency transaction accounting and balance-sheet translation.",
     "SSAP No. 23 follows the functional-currency approach — record at spot rate at transaction date; translate at period-end. Translation gains/losses flow through OCI / surplus.",
     "Provides consistent treatment of multi-currency operations for global insurers.",
     [("2001", "Original SSAP 23 issued.")],
     [("Translation", "ASC 830 — same approach", "Same", "Aligned")]),
    ("24", "Discontinued Operations", "Discontinued Ops",
     "Reporting of discontinued operations and held-for-sale classification.",
     "SSAP No. 24 governs reporting of discontinued operations including held-for-sale classification and disposal-group accounting.",
     "Separates results of discontinuing operations so analysts can evaluate continuing-operations performance.",
     [("2001", "Original SSAP 24 issued."), ("2015", "Aligned with ASU 2014-08.")],
     [("Discontinued ops", "ASC 205-20", "Same", "Aligned")]),
    ("25", "Affiliates and Other Related Parties", "Related Parties",
     "Related-party disclosures and affiliated transactions.",
     "SSAP No. 25 mandates disclosure of related-party transactions and identifies affiliated transactions subject to special accounting and Form B disclosure.",
     "Transparency around related-party arrangements is critical for solvency assessment.",
     [("2001", "Original SSAP 25 issued.")],
     [("Related-party disclosure", "ASC 850", "SSAP 25 + Holding Company Act", "Aligned principle")]),
    ("27", "Off-Balance-Sheet and Credit-Risk Disclosures", "Off-BS Disclosure",
     "Disclosure of off-balance-sheet exposures including financial guarantees and concentrations.",
     "SSAP No. 27 requires disclosure of off-balance-sheet financial-instrument exposures and credit-risk concentrations.",
     "Captures economic exposures not reflected in the balance sheet but material to solvency.",
     [("2001", "Original SSAP 27 issued.")],
     [("OBS disclosure", "ASC 825 + 460", "SSAP 27 disclosures", "Aligned")]),
    ("29", "Prepaid Expenses", "Prepaid",
     "Prepaid expenses are non-admitted under SAP.",
     "SSAP No. 29 makes prepaid expenses non-admitted assets — reduces surplus.",
     "Prepaid expenses cannot be liquidated to pay claims; non-admission preserves statutory conservatism.",
     [("2001", "Original SSAP 29 issued.")],
     [("Prepaid", "Asset under ASC", "Non-admitted", "Direct surplus haircut")]),
    ("32R", "Preferred Stock", "Investments — Preferred",
     "NAIC designation drives carrying value for preferred stock — perpetual NAIC 1-2 at amortized cost.",
     "SSAP No. 32R: perpetual preferred stock NAIC 1-2 at amortized cost; NAIC 3+ at lower of cost or fair value. Redeemable preferred follows debt-like treatment.",
     "Smooths preferred-stock volatility on solvency surplus while preserving credit-deterioration signals.",
     [("2001", "Original SSAP 32 issued."), ("2018", "Revised 32R.")],
     [("Perpetual preferred (NAIC 1-2)", "FV through P&L (ASC 321)", "Amortized cost", "STAT smooths"),
      ("Mandatorily redeemable preferred", "Liability (ASC 480)", "Treated similarly", "Aligned")]),
    ("34", "Investment Income Due and Accrued", "Investment Income",
     "Accrual of investment income; non-admission of overdue accruals.",
     "SSAP No. 34 governs accrual of interest, dividends, and other investment income. Income overdue 90+ days is non-admitted.",
     "Maintains accrual integrity by removing receivables unlikely to materialize.",
     [("2001", "Original SSAP 34 issued.")],
     [("Investment income accrual", "Standard accrual + ASC 326 ECL", "Accrual + 90-day cliff", "STAT cliff")]),
    ("35R", "Guaranty Fund and Other Assessments", "Assessments",
     "Recognition of state guaranty-fund assessments and other regulatory levies.",
     "SSAP No. 35R requires accrual of guaranty-fund and similar assessments when probable and estimable.",
     "Captures the cost of insurer-of-last-resort regimes that fund insolvent-carrier claims.",
     [("2001", "Original SSAP 35 issued."), ("2014", "Revised 35R.")],
     [("Assessment recognition", "ASC 405-30", "SSAP 35R", "Aligned")]),
    ("36", "Troubled Debt Restructuring", "TDR",
     "Restructured-debt accounting (legacy concept; eliminated under GAAP by ASU 2022-02).",
     "SSAP No. 36 retains TDR accounting for statutory purposes even after GAAP eliminated the concept.",
     "Captures concessions granted to troubled borrowers — relevant for insurer mortgage-loan portfolios.",
     [("2001", "Original SSAP 36 issued."), ("2022", "Note: GAAP eliminated TDR accounting (ASU 2022-02); STAT retains it.")],
     [("TDR", "Eliminated by ASU 2022-02", "Retained", "Material divergence post-2022")]),
    ("38", "Acquisition, Development and Construction (ADC) Loans", "ADC Loans",
     "Real-estate acquisition, development, and construction loans.",
     "SSAP No. 38 covers ADC loans on real estate. Recognition follows substance — if loan has real-estate-investment characteristics, classify accordingly.",
     "Distinguishes pure debt instruments from quasi-equity real-estate investments.",
     [("2001", "Original SSAP 38 issued.")],
     [("ADC classification", "ASC 310-30", "Substance over form", "Aligned principle")]),
    ("47", "Uninsured Plans", "ASO Plans",
     "Administrative-services-only (ASO) and uninsured plan accounting.",
     "SSAP No. 47 covers contracts where the insurer provides administrative services but does not bear insurance risk.",
     "Distinguishes pure administration revenue from insurance revenue for accurate insurance-leverage analysis.",
     [("2001", "Original SSAP 47 issued.")],
     [("ASO revenue", "Service revenue (ASC 606)", "SSAP 47 fee revenue", "Aligned principle")]),
    ("49", "Policy Loans", "Policy Loans",
     "Policy loans against permanent life-insurance contracts.",
     "SSAP No. 49 covers policy loans — secured by the policyholder's cash value. Recognized at unpaid principal; admitted to extent of cash value.",
     "Provides consistent accounting for loans inherent to permanent life products.",
     [("2001", "Original SSAP 49 issued.")],
     [("Policy loans", "ASC 944", "SSAP 49", "Aligned")]),
    ("52", "Deposit-Type Contracts", "Deposit Contracts",
     "Investment contracts not meeting insurance-risk threshold — deposit accounting.",
     "SSAP No. 52 governs deposit-type contracts (e.g., GIC, funding agreements) where insurance risk is minimal — accounted for as deposits.",
     "Distinguishes pure financial-instrument-like contracts from genuine insurance contracts.",
     [("2001", "Original SSAP 52 issued.")],
     [("Deposit accounting", "ASC 944 — deposit", "Same", "Aligned")]),
    ("53", "Property and Casualty Premium Income", "P&C Premium",
     "P&C premium recognition — written, earned, unearned tracking.",
     "SSAP No. 53 covers P&C premium recognition. Written premium booked at policy effective date; earned ratably over coverage period; unearned-premium reserve held until earned.",
     "Provides the revenue framework underlying combined-ratio analysis.",
     [("2001", "Original SSAP 53 issued.")],
     [("Premium recognition", "ASC 944-605", "SSAP 53", "Aligned")]),
    ("57", "Title Insurance", "Title Insurance",
     "Specialized accounting for title insurance — premium recognition at policy issuance.",
     "SSAP No. 57 governs title insurance — premium fully earned at policy issuance, with statutory premium reserves held thereafter.",
     "Title insurance economics differ from other P&C; specialized accounting prevents distortion.",
     [("2001", "Original SSAP 57 issued.")],
     [("Title premium", "Recognize at issuance", "Same with statutory reserves", "Aligned")]),
    ("58", "Mortgage Guaranty Insurance", "Mortgage Guaranty",
     "Specialized accounting for mortgage-guaranty insurance — countercyclical contingency reserves.",
     "SSAP No. 58 governs mortgage-guaranty insurance with the unique contingency-reserve requirement (50% of net earned premium) intended to absorb credit-cycle losses.",
     "Mortgage-guaranty insurance has long, countercyclical loss patterns demanding specialized reserving.",
     [("2001", "Original SSAP 58 issued.")],
     [("Contingency reserve", "Not required under GAAP", "50% of net earned premium", "STAT-unique")]),
    ("59", "Credit Life and Accident & Health Insurance", "Credit Life/A&H",
     "Specialized accounting for credit life and credit A&H contracts attached to debt.",
     "SSAP No. 59 governs credit-life and credit-A&H insurance — typically purchased to repay debt on death or disability.",
     "Credit-attached coverages have specialized economics; harmonized accounting ensures comparability.",
     [("2001", "Original SSAP 59 issued.")],
     [("Earnings pattern", "ASC 944", "Mortality-pattern earning", "Aligned")]),
    ("63", "Underwriting Pools and Associations Including Intercompany Pools", "Pools",
     "Accounting for participation in underwriting pools and associations.",
     "SSAP No. 63 covers participation in underwriting pools — the participant records its share of pool premium, losses, and expenses.",
     "Many P&C insurers participate in pools (e.g., FAIR plans); consistent accounting prevents off-balance-sheet treatment.",
     [("2001", "Original SSAP 63 issued.")],
     [("Pool participation", "Proportionate consolidation", "Same", "Aligned")]),
    ("64", "Offsetting and Netting of Assets and Liabilities", "Netting",
     "When assets and liabilities can be offset — strict right-of-offset criteria.",
     "SSAP No. 64 permits offsetting only when there is a legal right of offset, intent to offset, and the amounts are determinable. Master netting agreements may qualify.",
     "Prevents inflation/deflation of gross balances through inappropriate netting.",
     [("2001", "Original SSAP 64 issued.")],
     [("Right of offset", "ASC 210-20", "SSAP 64", "Aligned")]),
    ("66", "Retrospectively Rated Contracts", "Retro-rated",
     "Retrospectively rated insurance contracts — premium adjustments based on actual experience.",
     "SSAP No. 66 covers retrospectively rated contracts — premium is adjusted at the end of the experience period based on actual loss experience.",
     "Captures the true economic premium for retro-rated contracts where the policyholder ultimately bears most of the underwriting risk.",
     [("2001", "Original SSAP 66 issued.")],
     [("Retro premium", "Estimated and accrued", "Same", "Aligned")]),
    ("69", "Statement of Cash Flows", "Cash Flow",
     "Cash-flow statement format for statutory financial statements.",
     "SSAP No. 69 governs the statutory statement of cash flows — direct method only, with operating / investing / financing classification.",
     "Provides regulators with insight into liquidity dynamics independent of accrual-basis surplus.",
     [("2001", "Original SSAP 69 issued.")],
     [("Cash flow method", "Direct or indirect (ASC 230)", "Direct only", "STAT mandates direct")]),
    ("70", "Allocation of Expenses", "Expense Allocation",
     "Allocation of operating expenses across lines of business and product categories.",
     "SSAP No. 70 requires consistent allocation of expenses across lines of business per regulatory expense-exhibit reporting.",
     "Ensures comparability of line-of-business profitability metrics across insurers.",
     [("2001", "Original SSAP 70 issued.")],
     [("Expense allocation", "Generally not prescribed", "Insurance Expense Exhibit format", "STAT prescribed")]),
    ("71", "Policy Acquisition Costs and Commissions", "Commissions",
     "Commission accounting — generally expensed when incurred under SAP.",
     "SSAP No. 71 governs commission expense — expensed when incurred (no DAC asset under SAP).",
     "Implements the broad SAP principle of expensing acquisition costs; reinforces SSAP 4 non-admission.",
     [("2001", "Original SSAP 71 issued.")],
     [("Commission expense", "DAC capitalization (ASC 944-30)", "Expense when incurred", "Largest GAAP-STAT difference")]),
    ("73", "Health Care Delivery Assets — Supplies, Pharmaceuticals and Surgical Supplies, Durable Medical Equipment", "Healthcare Assets",
     "Health-care delivery assets at managed-care insurers.",
     "SSAP No. 73 covers health-care delivery assets — supplies, pharmaceuticals, durable medical equipment, etc.",
     "Provides specialized treatment for managed-care entities with vertically integrated delivery operations.",
     [("2001", "Original SSAP 73 issued.")],
     [("Healthcare assets", "ASC 330 (inventory)", "SSAP 73", "Aligned")]),
    ("74", "Insurance-Related Assessments", "Assessments",
     "Recognition of insurance-related assessments beyond guaranty-fund (e.g., second-injury, reinsurance superintendents).",
     "SSAP No. 74 recognizes insurance-related assessments when probable and estimable.",
     "Closes scope gaps not addressed by SSAP 35R.",
     [("2001", "Original SSAP 74 issued.")],
     [("Assessment recognition", "ASC 405-30", "SSAP 74", "Aligned")]),
    ("75", "Reinsurance Premium Receivables", "Reinsurance Receivables",
     "Reinsurance premium receivables — admission and aged-receivable rules.",
     "SSAP No. 75 governs reinsurance premium receivables — generally admitted unless overdue.",
     "Cross-reference to SSAP 6 for aging rules and SSAP 62R for risk-transfer evaluation.",
     [("2001", "Original SSAP 75 issued.")],
     [("Reinsurance receivable", "ASC 944-310 + CECL", "SSAP 75 with non-admit", "GAAP earlier")]),
    ("76", "Repurchase Agreements, Reverse Repos, and Dollar Repurchase Agreements", "Repos",
     "Repurchase agreements and reverse-repo accounting — secured borrowing vs sale treatment.",
     "SSAP No. 76 covers repos. Most repos are secured borrowings; certain repos with right to substitute collateral may be sales.",
     "Provides bright-line guidance on repo classification critical for liquidity-management programs.",
     [("2001", "Original SSAP 76 issued.")],
     [("Repo classification", "ASC 860 (transfers)", "SSAP 76", "Aligned")]),
    ("77", "Loaning of Securities", "Securities Lending",
     "Securities-lending program accounting — borrower vs lender perspective.",
     "SSAP No. 77 covers securities-lending arrangements. Lender retains the security on the balance sheet; collateral is recognized as a separate asset and corresponding liability.",
     "Securities lending is a meaningful yield enhancer for insurers; consistent accounting prevents off-balance-sheet treatment.",
     [("2001", "Original SSAP 77 issued.")],
     [("Sec lending", "ASC 860-30", "SSAP 77", "Aligned")]),
    ("78", "Health Maintenance Organizations and Other Managed Care Plans", "HMO",
     "HMO and managed-care plan accounting — capitation revenue and provider liabilities.",
     "SSAP No. 78 covers HMOs — capitation revenue earned over coverage period; incurred-but-not-reported claim liabilities held for medical services.",
     "Specialized accounting for managed-care entities whose economics differ from indemnity insurers.",
     [("2001", "Original SSAP 78 issued.")],
     [("HMO accounting", "ASC 944 (managed care)", "SSAP 78", "Aligned")]),
    ("81", "Software Revenue Recognition", "Software Revenue",
     "Software revenue recognition for insurance-tech operations.",
     "SSAP No. 81 covers software revenue recognition for insurance-related software products.",
     "Captures revenue from insurer-developed software offered to third parties.",
     [("2001", "Original SSAP 81 issued.")],
     [("Software revenue", "ASC 606 / 985-605", "SSAP 81", "Aligned")]),
    ("82", "Health Care Delivery Assets — Pharmacy and Similar", "Pharmacy",
     "Pharmacy and similar healthcare-delivery assets.",
     "SSAP No. 82 expands SSAP 73 coverage to additional healthcare delivery assets.",
     "Closes scope gaps for managed-care entities with deeper delivery integration.",
     [("2001", "Original SSAP 82 issued.")],
     [("Pharmacy assets", "ASC 330", "SSAP 82", "Aligned")]),
    ("83", "Cash Flow Statement Format Changes", "Cash Flow",
     "Format updates to the statutory cash-flow statement.",
     "SSAP No. 83 makes refinements to the cash-flow statement format introduced by SSAP 69.",
     "Improves transparency of investing and financing cash flows.",
     [("2001", "Original SSAP 83 issued.")],
     [("Cash flow detail", "Aligned ASC 230", "Same", "Aligned")]),
    ("84", "Health Care and Government Insured Plan Receivables", "Healthcare Receivables",
     "Health-care receivables from government-insured programs (Medicare, Medicaid).",
     "SSAP No. 84 covers receivables from government-insured plans including Medicare Risk Adjustment, Medicaid claim payments.",
     "Complex government receivable streams need specialized recognition and admission rules.",
     [("2001", "Original SSAP 84 issued.")],
     [("Government receivables", "ASC 326 + ASC 944", "SSAP 84", "Aligned")]),
    ("85", "Derivative Instruments — Disclosure Requirements", "Derivatives Disclosure",
     "Enhanced disclosure for derivative instruments.",
     "SSAP No. 85 mandates expanded disclosure of derivative positions, hedging programs, and counterparty exposures.",
     "Complements SSAP 86 with disclosure transparency required for solvency assessment.",
     [("2001", "Original SSAP 85 issued.")],
     [("Derivative disclosure", "ASC 815 disclosure", "SSAP 85", "Aligned")]),
    ("90", "Disclosure of Significant Risks and Uncertainties", "Disclosure",
     "Enhanced disclosure of significant risks and uncertainties beyond SSAP 1.",
     "SSAP No. 90 expands SSAP 1 risk-disclosure requirements with sector-specific guidance.",
     "Provides regulators and policyholders with deeper insight into emerging risks.",
     [("2001", "Original SSAP 90 issued.")],
     [("Risk disclosure", "ASC 275", "SSAP 90", "Aligned")]),
    ("91R", "Accounting for Transfers and Servicing of Financial Assets and Extinguishments of Liabilities", "Transfers",
     "Transfers of financial assets and extinguishment of liabilities — sale vs secured-borrowing tests.",
     "SSAP No. 91R aligns with ASC 860 for transfers and extinguishments. Sale treatment requires legal isolation, ability to pledge/exchange, and no continuing control.",
     "Critical for securitizations, factoring, and collateral pledging — distinguishes off-balance-sheet sales from secured borrowings.",
     [("2001", "Original SSAP 91 issued."), ("2014", "Revised 91R.")],
     [("Transfer test", "ASC 860", "SSAP 91R same framework", "Aligned")]),
    ("92", "Accounting for Postretirement Benefits Other Than Pensions", "OPEB",
     "Other postretirement employment benefits accounting (medical, life, etc.).",
     "SSAP No. 92 governs accounting for postretirement benefits other than pensions, with actuarial valuation and accrual.",
     "Long-term obligation recognition consistent with pension accounting.",
     [("2001", "Original SSAP 92 issued.")],
     [("OPEB accounting", "ASC 715", "SSAP 92", "Aligned")]),
    ("93", "Accounting for Pension Benefits", "Pensions",
     "Defined-benefit and defined-contribution pension accounting.",
     "SSAP No. 93 governs pension accounting — actuarial valuation for DB plans; accrual of contributions for DC plans.",
     "Captures the long-term insurer-employer obligations for benefit plans.",
     [("2001", "Original SSAP 93 issued.")],
     [("Pension accounting", "ASC 715", "SSAP 93", "Largely aligned")]),
    ("94R", "Transferable and Non-transferable State Tax Credits", "Tax Credits",
     "Recognition of state tax credits — transferable vs non-transferable.",
     "SSAP No. 94R governs state tax credits including renewable energy and historic preservation credits.",
     "Provides specific guidance for monetizable tax positions distinct from federal tax accounting.",
     [("2001", "Original SSAP 94 issued."), ("2014", "Revised 94R.")],
     [("Tax credit recognition", "ASC 740 + ASC 740-30", "SSAP 94R", "Aligned principle")]),
    ("95", "Exchanges of Nonmonetary Assets", "Exchanges",
     "Accounting for exchanges of nonmonetary assets.",
     "SSAP No. 95 covers nonmonetary exchanges — generally fair-value-based recognition with limited exceptions.",
     "Aligned with broader nonmonetary-exchange principles to prevent gain manipulation.",
     [("2001", "Original SSAP 95 issued.")],
     [("Nonmonetary exchange", "ASC 845", "SSAP 95", "Aligned")]),
    ("96", "Settlement Requirements for Intercompany Transactions", "Intercompany",
     "Settlement and reconciliation requirements for intercompany transactions.",
     "SSAP No. 96 mandates timely settlement of intercompany balances within an insurance group.",
     "Prevents indefinite buildup of intercompany balances that obscure economic substance.",
     [("2001", "Original SSAP 96 issued.")],
     [("Intercompany settlement", "Eliminated in consolidation", "Settled per SSAP 96", "STAT-specific operational rule")]),
    ("97", "Investments in Subsidiary, Controlled and Affiliated Entities", "Affiliated Investments",
     "Equity-method accounting for subsidiaries, controlled entities, and affiliates ('SCA').",
     "SSAP No. 97 mandates equity-method accounting for SCAs — investee statutory financials drive carrying value.",
     "Provides consistent recognition of affiliate interests at the parent level.",
     [("2001", "Original SSAP 97 issued.")],
     [("Affiliate investment", "Consolidation (ASC 810) or equity method", "Equity method (SSAP 97)", "GAAP consolidates; STAT does not")]),
    ("100R", "Fair Value", "Fair Value",
     "Fair-value measurement framework for SAP.",
     "SSAP No. 100R adopts the ASC 820 fair-value framework — exit price, hierarchy of inputs (Level 1/2/3).",
     "Provides consistent fair-value framework across investment, derivative, and other measurements.",
     [("2010", "Original SSAP 100 issued."), ("2018", "Revised 100R aligned with ASC 820 updates.")],
     [("FV framework", "ASC 820", "SSAP 100R", "Aligned")]),
    ("102", "Postretirement and Postemployment Benefits", "OPEB",
     "Postretirement and postemployment benefit accounting (combined).",
     "SSAP No. 102 consolidates postretirement and postemployment benefit accounting.",
     "Streamlined guidance covering all post-employment obligations.",
     [("2012", "Original SSAP 102 issued.")],
     [("Post-employment", "ASC 715 / 712", "SSAP 102", "Aligned")]),
    ("103R", "Transfers and Servicing of Financial Assets and Extinguishments of Liabilities", "Transfers",
     "Updated transfer accounting following ASC 860 amendments.",
     "SSAP No. 103R updates SSAP 91R to align with subsequent ASC 860 amendments.",
     "Maintains alignment with GAAP transfer-accounting framework.",
     [("2014", "Original SSAP 103 issued.")],
     [("Transfer accounting", "ASC 860 current", "SSAP 103R", "Aligned")]),
    ("104R", "Share-Based Payments", "Share-Based Comp",
     "Stock-based compensation accounting for insurance-entity employees.",
     "SSAP No. 104R covers stock options, restricted-stock units, and similar share-based payment arrangements.",
     "Provides consistent recognition of share-based compensation as an expense.",
     [("2014", "Original SSAP 104 issued.")],
     [("Share-based comp", "ASC 718", "SSAP 104R", "Aligned")]),
    ("106", "Affordable Care Act Section 9010 Assessment", "ACA",
     "ACA health-insurer fee accounting (now repealed).",
     "SSAP No. 106 governs the ACA Section 9010 health-insurer fee — repealed effective 2021.",
     "Historical guidance retained for legacy financial statements.",
     [("2014", "Original SSAP 106 issued."), ("2021", "Underlying ACA fee repealed.")],
     [("ACA fee", "Operating expense", "Same", "Aligned")]),
    ("107", "Risk-Sharing Provisions of the Affordable Care Act", "ACA Risk Programs",
     "Accounting for ACA risk-corridors, risk-adjustment, and reinsurance programs.",
     "SSAP No. 107 covers the three ACA risk-sharing programs — risk corridors, risk adjustment, and transitional reinsurance.",
     "Provides specialized accounting for ACA-specific risk-sharing arrangements affecting health insurer balance sheets.",
     [("2014", "Original SSAP 107 issued.")],
     [("ACA risk programs", "ASC 944 + ACA-specific", "SSAP 107", "Aligned")]),
    ("108", "Derivatives Hedging Variable Annuity Guarantees", "VA Hedging",
     "Specialized hedge accounting for derivatives hedging variable-annuity guarantees.",
     "SSAP No. 108 provides relief for derivatives hedging variable-annuity guarantees, allowing fair-value hedge treatment with smoother surplus impact.",
     "Recognizes the unique nature of VA-guarantee hedging programs and aligns accounting with economic intent.",
     [("2017", "Original SSAP 108 issued.")],
     [("VA hedging", "ASC 815 + LDTI MRB", "SSAP 108 with VM-21", "Both have specialized treatment")]),
    ("109", "Wash Sales", "Wash Sales",
     "Wash-sale accounting for investment transactions.",
     "SSAP No. 109 governs wash sales — sale and reacquisition of substantially identical securities. Loss not recognized; basis adjusted.",
     "Prevents tax-driven loss harvesting from inflating reported losses.",
     [("2018", "Original SSAP 109 issued.")],
     [("Wash sale", "Tax rule (IRC §1091)", "SSAP 109", "STAT mirrors tax")]),
    ("110", "Variable Interest Entities (VIEs)", "VIEs",
     "Variable interest entity consolidation analysis for SAP.",
     "SSAP No. 110 follows ASC 810 VIE consolidation rules with statutory-specific overlays.",
     "Captures off-balance-sheet entity exposures consistent with GAAP framework.",
     [("2020", "Original SSAP 110 issued.")],
     [("VIE consolidation", "ASC 810", "SSAP 110", "Aligned")]),
    ("111", "Joint Ventures", "JVs",
     "Joint-venture accounting clarifications.",
     "SSAP No. 111 provides joint-venture-specific recognition guidance complementing SSAP 48.",
     "Closes ambiguity around joint-venture vs equity-method distinction.",
     [("2020", "Original SSAP 111 issued.")],
     [("JV accounting", "ASC 323", "SSAP 111", "Aligned")]),
    ("112", "ASU 2016-02 Lease Implementation", "Leases",
     "Statutory implementation of ASC 842 leasing.",
     "SSAP No. 112 (now 22R) implemented ASC 842 lessee accounting for SAP — see SSAP 22R for current rules.",
     "Brought lease accounting into alignment with GAAP while preserving statutory non-admission of operating ROU.",
     [("2019", "Issued; later folded into SSAP 22R.")],
     [("Lease implementation", "ASC 842", "SSAP 22R + non-admit", "STAT non-admits ROU")]),
    ("113", "Transferred Lottery Prizes", "Lottery Prizes",
     "Specialized accounting for transferred lottery prize obligations.",
     "SSAP No. 113 covers structured-settlement obligations involving lottery-prize payment streams.",
     "Specialized guidance for niche structured-settlement portfolio.",
     [("2020", "Original SSAP 113 issued.")],
     [("Structured settlement", "ASC 944", "SSAP 113", "Aligned")]),
    ("114", "Accounting for Goodwill", "Goodwill",
     "Goodwill recognition and impairment specifically for SAP entities.",
     "SSAP No. 114 supplements SSAP 68 with goodwill-specific recognition and impairment rules.",
     "Reinforces statutory goodwill admission limits via the 10% rule.",
     [("2020", "Original SSAP 114 issued.")],
     [("Goodwill", "ASC 805 + impairment testing", "SSAP 68/114 + 10% admission", "STAT severely limits")]),
    ("115", "Accounting for Pension and Postretirement Benefit Plan Settlements", "Pension Settlements",
     "Settlement and curtailment accounting for pension and OPEB plans.",
     "SSAP No. 115 covers gains and losses on pension plan settlements (e.g., lump-sum cashouts) and curtailments.",
     "Captures one-time impacts of pension-program restructuring on surplus.",
     [("2021", "Original SSAP 115 issued.")],
     [("Settlement accounting", "ASC 715-30-35", "SSAP 115", "Aligned")]),
    ("116", "Reference Rate Reform (LIBOR Transition)", "LIBOR",
     "Optional expedients for the LIBOR-to-SOFR transition.",
     "SSAP No. 116 provides expedients for contracts modified due to LIBOR cessation, allowing the modification to be treated as continuation rather than extinguishment.",
     "Eased the operational burden of the LIBOR-to-SOFR transition (2021-2023) for insurance investments and derivatives.",
     [("2020", "Original SSAP 116 issued."), ("2023", "LIBOR cessation completed; expedients sunset.")],
     [("Reference rate reform", "ASC 848", "SSAP 116", "Aligned")]),
    ("117", "Accounting for Cryptoassets", "Crypto",
     "Cryptoasset recognition — generally limited admission.",
     "SSAP No. 117 establishes that cryptoassets are non-admitted unless specifically authorized; no carrying basis prescribed for admitted crypto.",
     "Conservatism: cryptoassets exhibit volatility and liquidity risk inconsistent with statutory accounting principles.",
     [("2024", "Original SSAP 117 issued.")],
     [("Cryptoassets", "ASU 2023-08 — fair value", "Generally non-admitted", "STAT excludes")]),
    ("118", "Reference Manual for Insurance Products", "Reference Manual",
     "Authoritative reference manual cross-references for insurance product accounting.",
     "SSAP No. 118 provides cross-references and integrating guidance for insurance product accounting.",
     "Provides traceability across SSAPs for complex multi-product analyses.",
     [("2024", "Original SSAP 118 issued.")],
     [("Cross-reference", "N/A", "STAT-only construct", "Specific to NAIC manual")]),
    ("119", "Climate Risk Disclosures", "Climate",
     "Climate-risk disclosure framework integrated with NAIC Climate Risk Disclosure Survey.",
     "SSAP No. 119 codifies climate-risk disclosure requirements aligned with TCFD and NAIC's annual survey.",
     "Brings climate-disclosure requirements into the formal SAP framework.",
     [("2024", "Original SSAP 119 issued."), ("2026", "Mandatory for all NAIC-reporting insurers.")],
     [("Climate disclosure", "SEC climate rule", "SSAP 119 + NAIC survey", "Both required")]),
    ("120", "Special Purpose Vehicles for Reinsurance", "SPVs",
     "Accounting for special-purpose vehicles used for reinsurance and capital relief.",
     "SSAP No. 120 governs special-purpose vehicles (SPVs) used for reinsurance, including XXX/AXXX securitizations and cat-bond SPVs.",
     "Captures emerging SPV structures used for regulatory capital relief.",
     [("2025", "Original SSAP 120 issued.")],
     [("Reinsurance SPV", "ASC 944-20 + ASC 810", "SSAP 120 + SSAP 62R", "Aligned principle")]),
    ("121", "Insurance-Linked Securities (ILS)", "ILS",
     "Accounting for insurance-linked securities including catastrophe bonds and sidecars.",
     "SSAP No. 121 covers insurance-linked securities — cat bonds, sidecars, ILW (industry-loss warranties), and similar instruments.",
     "Captures ILS-specific economics distinct from traditional reinsurance.",
     [("2025", "Original SSAP 121 issued.")],
     [("ILS accounting", "ASC 944-20 / ASC 815", "SSAP 121", "Aligned principle")]),
    ("122", "Principle-Based Reserves for Small Life Companies", "PBR Small Co",
     "Simplified PBR framework for small life-insurance companies.",
     "SSAP No. 122 provides a simplified principle-based-reserves framework for small life companies that may otherwise be overburdened by full VM-20 implementation.",
     "Permits proportionate compliance based on company size and complexity, reducing implementation cost for small insurers.",
     [("2025", "Original SSAP 122 issued."), ("2026", "Effective for small life insurers below the size threshold.")],
     [("PBR for small co", "Same LDTI requirements", "Simplified VM-20", "STAT scales by size")]),
]


def build_ssap():
    detailed = json.loads((FRONT / "ssap.json").read_text())
    existing_ids = {s["id"] for s in detailed["standards"]}
    # Add source_link to each existing entry
    for s in detailed["standards"]:
        n = s["number"].replace("R", "")
        s.setdefault("source_link",
                     f"{NAIC_BASE}/SSAP%20{s['number']}.pdf")
    for n, title, fsli, summary, chap, need, evo, comp in SSAP_ENTRIES:
        sid = f"SSAP-{n}"
        if sid in existing_ids:
            continue
        slug_n = n.replace("R", "")
        detailed["standards"].append({
            "id": sid,
            "number": n,
            "title": title,
            "fsli": fsli,
            "summary": summary,
            "chapter_content": chap,
            "need": need,
            "evolution": [{"year": y, "change": c} for y, c in evo],
            "gaap_comparison": [
                {"aspect": a, "gaap": g, "stat": s_, "delta": d}
                for a, g, s_, d in comp
            ],
            "source_link": f"{NAIC_BASE}/SSAP%20{n}.pdf",
            "tags": [fsli, "SSAP"],
        })
    # Sort by numeric SSAP number for usability
    def sort_key(s):
        raw = s["number"].replace("R", "").rstrip()
        try:
            return int(raw)
        except Exception:
            return 999
    detailed["standards"].sort(key=sort_key)
    detailed["source_url"] = "https://content.naic.org/sites/default/files/inline-files/Accounting%20Practices%20and%20Procedures%20Manual.pdf"
    (FRONT / "ssap.json").write_text(json.dumps(detailed, indent=2))
    (BACK / "ssap.json").write_text(json.dumps(detailed, indent=2))
    print(f"SSAP: {len(detailed['standards'])} entries")


# ---------------------------------------------------------------------------
# ASC 944 — additional sub-topics to fill out 944-X coverage
# ---------------------------------------------------------------------------

ASC944_NEW = [
    ("944-205", "Presentation of Financial Statements", "Presentation",
     "Insurance-specific income-statement and balance-sheet presentation requirements.",
     "ASC 944-205 establishes the presentation of insurance-entity financial statements — separate captions for premium revenue, benefits & claims, DAC amortization, and reinsurance impacts.",
     "Provides users with comparable, standardized financial-statement presentation across insurance entities.",
     [("2009", "Codified from prior guidance.")],
     [("Presentation", "ASC 944-205", "Insurance Annual Statement format", "Different formats; same elements")]),
    ("944-210", "Balance Sheet", "Balance Sheet",
     "Insurance balance-sheet classification and presentation.",
     "ASC 944-210 specifies balance-sheet classification — separate accounts, policyholder reserves, DAC, reinsurance recoverables, and insurance-related receivables.",
     "Standardized line-item presentation.",
     [("2009", "Codified from FAS 60 / 97.")],
     [("Balance sheet", "ASC 944-210", "Annual Statement format", "Different formats; aligned content")]),
    ("944-225", "Income Statement", "Income Statement",
     "Insurance-specific income-statement classification.",
     "ASC 944-225 specifies income-statement classification — premium revenue, benefits, DAC amortization, investment income, and reinsurance impacts.",
     "Standardized income-statement format for insurance entities.",
     [("2009", "Codified from FAS 60.")],
     [("Income statement", "ASC 944-225", "Different STAT format", "Different formats; aligned elements")]),
    ("944-235", "Notes to Financial Statements", "Notes",
     "Insurance-specific note disclosures.",
     "ASC 944-235 mandates insurance-specific note disclosures — reserve rollforwards, reinsurance disclosure, MRB rollforward, and DAC rollforward.",
     "Provides users with the granular disclosure needed to evaluate insurer performance and risk.",
     [("2009", "Codified."), ("2018", "ASU 2018-12 expanded LDTI disclosures.")],
     [("Note disclosures", "ASC 944-235 + ASU 2018-12", "Annual Statement notes", "Both extensive; different formats")]),
    ("944-250", "Accounting Changes and Error Corrections", "Accounting Changes",
     "Accounting-change and error-correction guidance specific to insurance.",
     "ASC 944-250 provides insurance-specific guidance on accounting changes (e.g., LDTI transition) and error corrections.",
     "Coordinates broad ASC 250 with insurance-specific transition mechanics.",
     [("2018", "ASU 2018-12 transition guidance issued."), ("2023", "Effective for SEC filers.")],
     [("Accounting changes", "ASC 944-250 + ASC 250", "SSAP 3 framework", "Aligned principle")]),
    ("944-255", "Changing Prices", "Inflation",
     "Inflation-adjusted disclosure (largely historical).",
     "ASC 944-255 covers historical changing-price disclosures (largely retired).",
     "Historical guidance retained for legacy reporting.",
     [("2009", "Codified.")],
     [("Inflation disclosure", "Largely historical", "N/A", "Historical")]),
    ("944-275", "Risks and Uncertainties", "Risks",
     "Risk-and-uncertainty disclosures for insurers.",
     "ASC 944-275 mandates disclosure of significant risks and uncertainties including catastrophe exposure, concentration of insured risks, and reserve estimation uncertainty.",
     "Provides users with insight into the inherent uncertainty in insurance financial statements.",
     [("2009", "Codified from FAS 5.")],
     [("Risk disclosure", "ASC 944-275 + ASC 275", "SSAP 1 / 90", "Aligned")]),
    ("944-440", "Commitments", "Commitments",
     "Insurance-specific commitments and contingencies.",
     "ASC 944-440 covers insurance-specific commitments — investment commitments, reinsurance commitments, and lease commitments specific to insurance operations.",
     "Captures off-balance-sheet commitments material to solvency.",
     [("2009", "Codified.")],
     [("Commitments", "ASC 944-440 + ASC 440", "SSAP 5R + 27", "Aligned")]),
    ("944-470", "Debt", "Debt",
     "Insurance-entity debt classification and presentation.",
     "ASC 944-470 covers debt issued by insurance entities — long-term debt, surplus notes (where applicable), and trust-preferred securities.",
     "Standardizes debt presentation across insurance issuers.",
     [("2009", "Codified.")],
     [("Insurer debt", "ASC 470", "SSAP 15 / 41R for surplus notes", "Surplus notes are STAT-specific")]),
    ("944-505", "Equity", "Equity",
     "Insurance-entity equity classification and dividend mechanics.",
     "ASC 944-505 covers equity classification and dividend mechanics specific to insurance entities — dividend restrictions, retained earnings analysis, and AOCI components.",
     "Captures the regulatory dividend restrictions applicable to insurance entities.",
     [("2009", "Codified.")],
     [("Equity / surplus", "ASC 944-505 + ASC 505", "SSAP 72", "GAAP equity vs STAT surplus differ materially")]),
    ("944-740", "Income Taxes", "Tax",
     "Insurance-specific income-tax considerations.",
     "ASC 944-740 covers insurance-specific income-tax matters including IRC §846 loss-reserve discounting, IRC §848 DAC tax-amortization, and FBE/non-FBE life-insurance company classification.",
     "Captures the unique tax-accounting issues facing insurance entities.",
     [("2009", "Codified."), ("2017", "TCJA — material insurer-specific changes.")],
     [("Insurer tax", "ASC 944-740 + ASC 740", "SSAP 101", "Both leverage federal tax basis with admission overlay")]),
    ("944-805", "Business Combinations", "Business Combinations",
     "Business combinations involving insurance entities — VOBA recognition.",
     "ASC 944-805 governs business combinations involving insurance entities, with the unique requirement to recognize VOBA at fair value.",
     "Addresses the asymmetry that would otherwise occur when an acquirer takes on insurance liabilities at fair value but no offsetting asset.",
     [("2009", "Codified."), ("2018", "VOBA amortization aligned with LDTI.")],
     [("Insurance M&A", "ASC 944-805 + ASC 805", "SSAP 68 with goodwill cap", "GAAP recognizes VOBA; STAT does not")]),
    ("944-815", "Derivatives and Hedging", "Derivatives",
     "Insurance-specific derivative and hedging considerations.",
     "ASC 944-815 cross-references ASC 815 with insurance-specific overlays — embedded derivatives in insurance hosts, MRB hedging, and replication transactions.",
     "Captures insurance-specific derivative use cases distinct from general financial-instrument framework.",
     [("2009", "Codified."), ("2018", "ASU 2018-12 introduced MRBs.")],
     [("Derivatives", "ASC 944-815 + ASC 815", "SSAP 86", "STAT permits more hedge-accounting flexibility")]),
    ("944-820", "Fair Value Measurement", "Fair Value",
     "Insurance-specific fair-value-measurement considerations.",
     "ASC 944-820 cross-references ASC 820 with insurance-specific overlays for Level 3 valuations and unique insurance-contract fair values.",
     "Captures the fair-value-measurement challenges unique to insurance — MRBs, illiquid insurance receivables, and Level 3 investment portfolios.",
     [("2009", "Codified."), ("2011", "Aligned with ASC 820 modernization.")],
     [("Fair value framework", "ASC 944-820 + ASC 820", "SSAP 100R", "Aligned")]),
]


def build_asc944():
    detailed = json.loads((FRONT / "asc944.json").read_text())
    existing_ids = {s["id"] for s in detailed["standards"]}
    for s in detailed["standards"]:
        s.setdefault("source_link",
                     f"https://asc.fasb.org/{s['number'].replace('944-', '944/topic&trid=2156436#')}")
    for n, title, fsli, summary, chap, need, evo, comp in ASC944_NEW:
        sid = f"ASC-{n}"
        if sid in existing_ids:
            continue
        detailed["standards"].append({
            "id": sid,
            "number": n,
            "title": title,
            "fsli": fsli,
            "summary": summary,
            "chapter_content": chap,
            "need": need,
            "evolution": [{"year": y, "change": c} for y, c in evo],
            "gaap_comparison": [
                {"aspect": a, "gaap": g, "stat": s_, "delta": d}
                for a, g, s_, d in comp
            ],
            "source_link": f"https://asc.fasb.org/944/{n}",
            "tags": [fsli, "ASC 944"],
        })
    detailed["standards"].sort(key=lambda s: s["number"])
    (FRONT / "asc944.json").write_text(json.dumps(detailed, indent=2))
    (BACK / "asc944.json").write_text(json.dumps(detailed, indent=2))
    print(f"ASC 944: {len(detailed['standards'])} entries")


# ---------------------------------------------------------------------------
# PCAOB — full insurance-relevant AS list
# ---------------------------------------------------------------------------

PCAOB_NEW = [
    ("AS 1101", "Audit Risk", "Audit Framework",
     "Concept of audit risk — risk of material misstatement combined with detection risk.",
     "AS 1101 defines audit risk as the risk of issuing an unqualified opinion on materially misstated financial statements. For insurance audits, this includes risks around reserves, investments, and reinsurance.",
     "Establishes the conceptual framework that drives audit-evidence sufficiency.",
     [("2003", "Adopted."), ("2015", "Reorganized into AS 1101 numbering.")],
     [("Audit risk model", "AS 1101", "AICPA AU-C 200", "Aligned")]),
    ("AS 1105", "Audit Evidence", "Audit Evidence",
     "Definition and types of audit evidence — sufficiency and appropriateness.",
     "AS 1105 establishes that auditors need sufficient appropriate evidence. For insurance, evidence includes actuarial reports, reinsurance contracts, investment confirmations, and management representations.",
     "Without standards on evidence quality, audits could rely on management assertions alone.",
     [("2010", "Adopted as AS 15."), ("2015", "Reorganized as AS 1105.")],
     [("Evidence sufficiency", "AS 1105", "AICPA AU-C 500", "Aligned")]),
    ("AS 1201", "Supervision of the Audit Engagement", "Supervision",
     "Engagement supervision and review responsibilities.",
     "AS 1201 governs supervision and review including assigning work, supervising junior staff, and reviewing engagement performance. Especially important for insurance audits where complex actuarial work is delegated.",
     "Quality control depends on adequate supervision; without it, junior staff judgments can dominate.",
     [("2010", "Adopted."), ("2015", "Reorganized.")],
     [("Audit supervision", "AS 1201", "AICPA AU-C 220", "Aligned")]),
    ("AS 1215", "Audit Documentation", "Documentation",
     "Audit documentation requirements — sufficient detail to enable an experienced auditor to understand procedures performed.",
     "AS 1215 mandates audit documentation be sufficient for an experienced auditor to understand the work performed, evidence obtained, and conclusions reached.",
     "Documentation is the auditor's primary defense in regulatory inspections and litigation.",
     [("2003", "Original."), ("2015", "Reorganized as AS 1215.")],
     [("Documentation", "AS 1215", "AICPA AU-C 230", "Aligned")]),
    ("AS 2305", "Substantive Analytical Procedures", "Analytical Procedures",
     "Use of analytical procedures as substantive evidence.",
     "AS 2305 governs the use of analytical procedures as substantive audit evidence — particularly relevant for premium-revenue testing and ratio analysis at insurance companies.",
     "Provides efficiency in audit testing by leveraging predictable account relationships.",
     [("2010", "Adopted."), ("2015", "Reorganized.")],
     [("Analytical procedures", "AS 2305", "AICPA AU-C 520", "Aligned")]),
    ("AS 2410", "Related Parties", "Related Parties",
     "Audit procedures for related-party transactions.",
     "AS 2410 (effective 2014) establishes audit procedures for related-party transactions including identifying related parties, evaluating significant transactions, and concluding on financial-statement effects. Critical for insurer captive transactions.",
     "Related parties are a leading source of fraud risk; rigorous audit procedures are essential.",
     [("2014", "AS 2410 issued — significantly expanded prior guidance.")],
     [("Related parties audit", "AS 2410", "AICPA AU-C 550", "Aligned")]),
    ("AS 2415", "Going Concern", "Going Concern",
     "Auditor's evaluation of going-concern uncertainty.",
     "AS 2415 requires the auditor to evaluate whether substantial doubt exists about the entity's ability to continue as a going concern within 12 months of issuance. For insurers, RBC, capital adequacy, and reserve adequacy are key indicators.",
     "Going-concern risk is among the most material judgments an auditor makes; structured guidance ensures consistency.",
     [("2003", "AS 1015 / AU 341."), ("2015", "Reorganized as AS 2415."), ("2017", "Aligned with ASU 2014-15 (Subtopic 205-40).")],
     [("Going concern", "AS 2415", "AICPA AU-C 570", "Aligned")]),
    ("AS 2503", "Auditing Investments in Securities", "Investments Audit",
     "Specialized audit guidance for investments in securities.",
     "AS 2503 (consolidated into AS 2501 in 2018) provided specialized guidance for auditing investments in securities — confirmations, fair-value testing, classification verification.",
     "Securities portfolio audits are central to insurance audits; specific guidance was previously needed.",
     [("2003", "Original AS 13."), ("2018", "Consolidated into AS 2501.")],
     [("Securities audit", "AS 2501 (post-2018)", "AICPA AU-C 540 / 501", "Aligned")]),
    ("AS 2701", "XBRL Data Tags", "XBRL",
     "Auditor consideration of XBRL data tags filed with the SEC.",
     "AS 2701 governs auditor procedures over XBRL data — interactive data tags filed with the SEC alongside human-readable financial statements.",
     "XBRL is the machine-readable financial-statement representation used by analysts, regulators, and platforms.",
     [("2009", "Original."), ("2015", "Reorganized.")],
     [("XBRL audit", "AS 2701 — SEC Issuer Companies", "AICPA — non-issuers", "Aligned for SEC filers")]),
    ("AS 2705", "Required Supplementary Information", "RSI",
     "Auditor procedures over required supplementary information accompanying audited financial statements.",
     "AS 2705 covers required supplementary information (RSI) — most prominently for insurance, the long-duration contract disclosures introduced by ASU 2018-12.",
     "RSI provides users with information not subject to the same audit rigor as the financial statements; clear standards prevent confusion.",
     [("2010", "Adopted."), ("2015", "Reorganized.")],
     [("RSI procedures", "AS 2705", "AICPA AU-C 730", "Aligned")]),
    ("AS 4101", "Responsibilities Regarding Filings Under Federal Securities Statutes", "SEC Filings",
     "Auditor responsibilities for SEC filings beyond the financial statements.",
     "AS 4101 covers auditor responsibilities for registration statements, proxy statements, and other SEC filings incorporating audited financial statements.",
     "Provides clarity on the auditor's role in filings beyond the 10-K and 10-Q.",
     [("2003", "Original AS 8."), ("2015", "Reorganized as AS 4101.")],
     [("SEC filings", "AS 4101", "Not applicable", "PCAOB-only construct")]),
]


def build_pcaob():
    detailed = json.loads((FRONT / "pcaob.json").read_text())
    existing_ids = {s["id"] for s in detailed["standards"]}
    for s in detailed["standards"]:
        s.setdefault("source_link", f"{PCAOB_BASE}/{s['number'].lower().replace(' ', '-')}")
    for n, title, fsli, summary, chap, need, evo, comp in PCAOB_NEW:
        sid = f"PCAOB-{n.replace(' ', '-')}"
        if sid in existing_ids:
            continue
        detailed["standards"].append({
            "id": sid,
            "number": n,
            "title": title,
            "fsli": fsli,
            "summary": summary,
            "chapter_content": chap,
            "need": need,
            "evolution": [{"year": y, "change": c} for y, c in evo],
            "gaap_comparison": [
                {"aspect": a, "gaap": g, "stat": s_, "delta": d}
                for a, g, s_, d in comp
            ],
            "source_link": f"{PCAOB_BASE}/{n.lower().replace(' ', '-')}",
            "tags": [fsli, "PCAOB"],
        })
    detailed["standards"].sort(key=lambda s: s["number"])
    (FRONT / "pcaob.json").write_text(json.dumps(detailed, indent=2))
    (BACK / "pcaob.json").write_text(json.dumps(detailed, indent=2))
    print(f"PCAOB: {len(detailed['standards'])} entries")


if __name__ == "__main__":
    build_ssap()
    build_asc944()
    build_pcaob()
